---
- hosts: mikrotik
  connection: network_cli
  gather_facts: no
  tasks:
  - name: Setup Interface name #rename interface fisik
    routeros_command:
      commands:
        - /interface set ether1 name=ether1-internet
        - /interface set ether3 name=ether3-fortigate
        - /interface set ether5 name=ether5-RVPN
